"use strict";
const {chromium}=require("C:/Users/Keisuke/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright");
const assert=require("node:assert/strict");
const path=require("node:path");
const os=require("node:os");
(async()=>{
 const browser=await chromium.launch({headless:true,executablePath:"C:/Program Files/Google/Chrome/Application/chrome.exe"});
 try {
  for(const width of [360,390]) {
   const context=await browser.newContext({viewport:{width,height:844},isMobile:true,hasTouch:true});
   const page=await context.newPage();const errors=[];
   page.on('pageerror',e=>errors.push(e.message));
   await page.route('https://**/*',r=>r.abort());
   await page.goto('http://127.0.0.1:4182/index.html',{waitUntil:'networkidle'});
   const saved=()=>page.evaluate(()=>JSON.parse(localStorage.getItem('rice_os_v8_stable')));
   await page.evaluate(()=>window.RiceOS.state.saveFieldWork({fieldIds:[window.RiceOS.state.activeFields()[0].fieldId],date:'2026-10-02',workName:'草刈り',memo:'QA mowing icon'}));
   const before=await saved();
   const nav=name=>page.locator(`.nav-item[data-screen="${name}"]:visible`).click();
   await page.locator('[data-home-quick-record]').click();
   await page.locator('[data-sheet-add="shipment"]').click();
   assert.equal(await page.locator('#shipmentForm').count(),1);
   await page.locator('#shipmentDate').fill('2027-01-02');
   await page.locator('#shipmentSeason').fill('2026');
   await page.locator('#shipmentRecipient').fill('QA 身内 <試験>');
   await page.locator('#shipmentKind').selectOption('sale');
   await page.locator('#shipmentRiceType').selectOption('white');
   await page.locator('[data-shipment-bags]').first().fill('3');
   await page.locator('#shipmentPricePer60Kg').fill('24000');
   await page.locator('[data-shipment-add-package="10"]').click();
   await page.locator('[data-shipment-bags]').nth(1).fill('2');
   await page.locator('#shipmentMemo').fill('QAメモ');
   assert.ok((await page.locator('#shipmentPackageTotal').innerText()).includes('110'));
   await page.evaluate(()=>scrollTo(0,0));
   await page.screenshot({path:path.join(os.tmpdir(),`shipments-editor-${width}.png`)});
   assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
   await page.locator('#shipmentForm button[type="submit"]').click();
   let data=await saved();let row=data.shipments.find(r=>r.recipient==='QA 身内 <試験>');assert.ok(row);
   assert.deepEqual(row.packages.map(r=>[r.kg,r.bags]),[[30,3],[10,2]]);
   assert.equal(row.pricePer60Kg,24000);assert.equal(row.season,2026);
   assert.deepEqual(data.fieldWorks,before.fieldWorks);assert.deepEqual(data.irrigations,before.irrigations);assert.deepEqual(data.machines,before.machines);
   await page.screenshot({path:path.join(os.tmpdir(),`shipments-detail-${width}.png`)});
   await page.locator('[data-shipment-edit]').click();
   await page.locator('#shipmentRecipient').fill('cancelled');
   await page.locator('#appBackButton').click();
   assert.equal((await saved()).shipments.find(r=>r.shipmentId===row.shipmentId).recipient,'QA 身内 <試験>');
   await page.locator('[data-shipment-edit]').click();
   await page.locator('[data-shipment-bags]').first().fill('4');
   await page.locator('#shipmentForm button[type="submit"]').click();
   assert.equal((await saved()).shipments.find(r=>r.shipmentId===row.shipmentId).packages[0].bags,4);
   await page.locator('#appBackButton').click();
   await page.screenshot({path:path.join(os.tmpdir(),`shipments-list-${width}.png`)});
   assert.ok((await page.locator('.shipment-year-totals').innerText()).includes('140'));
   assert.ok((await page.locator('.shipment-year-totals').innerText()).includes('56,000'));
   await page.locator('[data-shipment-price-settings] > summary').click();
   await page.locator('#shipmentPriceRecipient').fill('QA 身内 <試験>');
   await page.locator('#shipmentPriceRate').fill('26000');
   await page.locator('[data-shipment-price-save]').click();
   await page.screenshot({path:path.join(os.tmpdir(),`shipments-rates-${width}.png`)});
   assert.equal((await saved()).shipments.find(r=>r.shipmentId===row.shipmentId).pricePer60Kg,24000,'Changing default does not rewrite history');
   assert.ok((await page.locator('.shipment-year-totals').innerText()).includes('56,000'));
   await page.locator('[data-shipment-new]').click();
   await page.locator('#shipmentRecipient').fill('QA 身内 <試験>');
   await page.locator('#shipmentRecipient').blur();
   assert.equal(await page.locator('#shipmentPricePer60Kg').inputValue(),'26000');
   await page.locator('#appBackButton').click();
   const rate=(await saved()).shipmentPrices.find(r=>r.recipient==='QA 身内 <試験>');
   assert.ok(rate);
   page.once('dialog',d=>d.dismiss());await page.locator(`[data-shipment-price-delete="${rate.priceId}"]`).click();assert.ok((await saved()).shipmentPrices.find(r=>r.priceId===rate.priceId));
   page.once('dialog',d=>d.accept());await page.locator(`[data-shipment-price-delete="${rate.priceId}"]`).click();assert.ok(!(await saved()).shipmentPrices.find(r=>r.priceId===rate.priceId));
   await page.locator(`[data-shipment-open="${row.shipmentId}"]`).click();
   await page.locator('[data-shipment-edit]').click();await page.locator('#shipmentKind').selectOption('gift');await page.locator('#shipmentForm button[type="submit"]').click();
   await page.locator('#appBackButton').click();assert.ok(!(await page.locator('.shipment-year-totals').innerText()).includes('56,000'),'Gifts excluded from sales');
   await page.locator(`[data-shipment-open="${row.shipmentId}"]`).click();
   page.once('dialog',d=>d.dismiss());await page.locator('[data-shipment-delete]').click();assert.ok((await saved()).shipments.find(r=>r.shipmentId===row.shipmentId));
   page.once('dialog',d=>d.accept());await page.locator('[data-shipment-delete]').click();assert.ok(!(await saved()).shipments.find(r=>r.shipmentId===row.shipmentId));
   await page.locator('#appBackButton').click();assert.equal(await page.locator('#screen-home.active').count(),1);
   await nav('annual');await page.locator('[data-annual-hub-view="work"]').click();
   await page.locator('[data-annual-work-scope="all"]').click();
   assert.equal(await page.locator('.annual-work-archive img[alt="草刈り作業"]').first().getAttribute('src'),'assets/images/light-icons/mowing-worker.png');
   await page.locator('[data-annual-shipments]').click();
   assert.equal(await page.locator('.shipment-ledger').count(),1);await page.locator('#appBackButton').click();assert.equal(await page.locator('[data-annual-hub-panel="work"]').count(),1);
   assert.deepEqual(errors,[]);console.log(`PASS shipments ${width}px bags/60kg price/recipient rates/snapshot/default/delete/cancel/back/data safety`);await context.close();
  }
 }finally{await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
