"use strict";
// Isolated browser storage; never connects to the user's browser profile.
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || "C:/Users/Keisuke/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright");
const path = require("node:path");
const fs = require("node:fs");
const os = require("node:os");
const assert = require("node:assert/strict");
(async () => {
  const browser = await chromium.launch({ headless: true, executablePath: process.env.CHROME_EXE || "C:/Program Files/Google/Chrome/Application/chrome.exe" });
  try {
    for (const width of [390,360]) {
    const context = await browser.newContext({viewport: {width,height:844},isMobile:true,hasTouch:true});
    const page = await context.newPage();
    const errors = [];
    page.on("pageerror", error => errors.push(error.message));
    await page.route("https://**/*", route => route.abort());
    await page.goto("http://127.0.0.1:4182/index.html", {waitUntil:"networkidle"});
    const out = path.join(os.tmpdir(), "rice-off-field-qa");
    fs.mkdirSync(out, {recursive:true});
    const saved = () => page.evaluate(() => JSON.parse(localStorage.getItem("rice_os_v8_stable")));
    const nav = name => page.locator(`.nav-item[data-screen="${name}"]:visible`).click();
    const open = async () => { await nav("home"); await page.locator("[data-home-quick-record]").click(); };
    if (process.argv.includes('--visual')) {
      await open(); await page.locator('[data-sheet-add="work"]').click();
      await page.locator('#sheetTargetMode').selectOption('group');
      const id=await page.locator('#sheetGroup option').evaluateAll(opts=>opts.find(o=>o.textContent.includes('亀石')).value);
      await page.locator('#sheetGroup').selectOption(id);
      const bounds=await page.locator('#sheetWorkFields button').evaluateAll(nodes=>nodes.slice(0,2).map(n=>({x:n.getBoundingClientRect().x,y:n.getBoundingClientRect().y})));
      assert.equal(bounds[0].y,bounds[1].y); assert.ok(bounds[1].x>bounds[0].x);
      await page.screenshot({path:path.join(out,`field-cards-${width}.png`)});
      await page.locator('#sheetOpenRecord').click();
      await page.locator('#fwTargetScope').selectOption('offField');
      assert.equal(await page.locator('#fieldWorkHeading').innerText(),'作業入力');
      await page.screenshot({path:path.join(out,`off-field-${width}.png`)});
      assert.deepEqual(errors,[]); await context.close(); console.log(`PASS ${width}px final two-column cards and scope heading`); continue;
    }
    await open();
    await page.locator('[data-sheet-add="work"]').click();
    await page.locator('#sheetWorkFields [data-sheet-field]').nth(0).click();
    await page.locator('#sheetWorkFields [data-sheet-field]').nth(1).click();
    assert.equal(await page.locator('#sheetWorkFields [aria-pressed="true"]').count(),2);
    await page.locator('#sheetOpenRecord').click();
    assert.equal(await page.locator('#fwFields .selected').count(),2);
    await page.locator('#fwTargetScope').selectOption('offField');
    assert.equal(await page.locator('#fwFields').isVisible(),false);
    await page.locator('#fwName').selectOption({label:'播種'});
    if (!await page.locator('#fwMemo').isVisible()) await page.locator('#fieldWorkForm summary').filter({hasText:'写真・メモ'}).click();
    await page.locator('#fwMemo').fill('QA off-field');
    await page.screenshot({path:path.join(out,`off-field-${width}.png`),fullPage:true});
    await page.locator('#fieldWorkForm button[type="submit"]').click();
    let data=await saved();
    let work=data.fieldWorks.find(w=>w.memo==='QA off-field');
    assert.ok(work); assert.equal(work.targetScope,'offField'); assert.deepEqual(work.fieldIds,[]); assert.deepEqual(work.batchFieldIds,[]);
    await nav('annual');
    await page.locator('[data-annual-work-scope="offField"]').click();
    await page.locator('.annual-work-archive summary').click();
    assert.ok((await page.locator('.annual-work-archive').innerText()).includes('QA off-field'));
    const row=page.locator('.annual-work-archive article').filter({hasText:'QA off-field'});
    await row.getByRole('button',{name:'編集',exact:true}).click();
    assert.equal(await page.locator('#fwTargetScope').inputValue(),'offField');
    if (!await page.locator('#fwMemo').isVisible()) await page.locator('#fieldWorkForm summary').filter({hasText:'写真・メモ'}).click();
    await page.locator('#fwMemo').fill('QA off-field edited');
    await page.locator('#fieldWorkForm button[type="submit"]').click();
    assert.equal((await saved()).fieldWorks.find(w=>w.workId===work.workId).memo,'QA off-field edited');
    await open();
    await page.locator('[data-sheet-add="schedule"]').click();
    await page.locator('#sheetScheduleTargetMode').selectOption('offField');
    await page.locator('#sheetScheduleTitle').fill('播種予定');
    await page.locator('#sheetScheduleForm button[type="submit"]').click();
    data=await saved(); const plan=data.schedules.find(s=>s.title==='播種予定');
    assert.ok(plan); assert.equal(plan.targetScope,'offField'); assert.deepEqual(plan.fieldIds,[]);
    await page.screenshot({path:path.join(out,`schedule-${width}.png`),fullPage:true});
    await page.locator(`[data-sheet-action="complete"][data-id="${plan.scheduleId}"]`).click();
    assert.equal(await page.locator('#fwTargetScope').inputValue(),'offField');
    assert.equal(await page.locator('#fwName').inputValue(),'播種');
    await page.locator('#fieldWorkForm button[type="submit"]').click();
    const completed=(await saved()).schedules.find(s=>s.scheduleId===plan.scheduleId);
    assert.ok(completed.completedByWorkId);
    assert.equal((await saved()).fieldWorks.find(w=>w.workId===completed.completedByWorkId).targetScope,'offField');
    await open();
    await page.locator('[data-sheet-add="schedule"]').click();
    await page.locator('#sheetScheduleTitle').fill('QA custom予定');
    await page.locator('#sheetScheduleTargetMode').selectOption('offField');
    await page.locator('#sheetScheduleForm button[type="submit"]').click();
    const customPlan=(await saved()).schedules.find(s=>s.title==='QA custom予定');
    await page.locator('#dateSheet [data-sheet-close]').last().click();
    await nav('calendar');
    await page.locator(`[data-calendar-action="complete"][data-id="${customPlan.scheduleId}"]`).click();
    assert.equal(await page.locator('#fwCustomName').inputValue(),'QA custom');
    await page.locator('#fieldWorkForm button[type="submit"]').click();
    assert.ok((await saved()).schedules.find(s=>s.scheduleId===customPlan.scheduleId).completedByWorkId);
    await nav('annual');
    await page.locator('[data-annual-work-scope="offField"]').click();
    await page.locator('.annual-work-archive summary').click();
    const del=page.locator(`[data-annual-action="delete"][data-id="${work.workId}"]`);
    page.once('dialog',dialog=>dialog.dismiss());
    await del.click();
    assert.ok((await saved()).fieldWorks.find(w=>w.workId===work.workId),'Cancel leaves record unchanged');
    page.once('dialog',dialog=>dialog.accept());
    await del.click();
    assert.ok(!(await saved()).fieldWorks.find(w=>w.workId===work.workId),'Delete removes only selected record');
    await open();
    await page.locator('[data-sheet-add="work"]').click();
    await page.locator('#sheetTargetMode').selectOption('group');
    const groupOption=await page.locator('#sheetGroup option').evaluateAll(options=>options.find(o=>o.textContent.includes('亀石')).value);
    await page.locator('#sheetGroup').selectOption(groupOption);
    assert.equal(await page.locator('#sheetWorkFields [aria-pressed="true"]').count(),3);
    await page.screenshot({path:path.join(out,`field-cards-${width}.png`)});
    await page.locator('#sheetOpenRecord').click();
    assert.equal(await page.locator('#fwFields .selected').count(),3);
    await page.locator('#fwName').selectOption('草刈り');
    await page.locator('#fieldWorkForm button[type="submit"]').click();
    assert.equal((await saved()).fieldWorks.find(w=>w.workName==='草刈り').fieldIds.length,3);
    await open();
    await page.locator('[data-sheet-add="schedule"]').click();
    await page.locator('#sheetScheduleTitle').fill('QA selected plan');
    const cards=page.locator('#sheetScheduleFields [data-sheet-field]');
    await cards.nth(0).click(); await cards.nth(2).click();
    const picked=await page.locator('#sheetScheduleFields [aria-pressed="true"]').evaluateAll(nodes=>nodes.map(n=>n.dataset.sheetField));
    assert.equal(picked.length,2);
    await page.locator('#sheetScheduleForm button[type="submit"]').click();
    const plans=(await saved()).schedules.filter(s=>s.title==='QA selected plan');
    assert.equal(plans.length,2);
    assert.deepEqual(plans.flatMap(s=>s.fieldIds).sort(),picked.sort());
    const size=await page.evaluate(()=>({scroll:document.documentElement.scrollWidth,client:document.documentElement.clientWidth}));
    assert.equal(size.scroll,size.client,'No horizontal overflow');
    console.log("SCREENSHOT_DIR="+out);
    assert.deepEqual(errors, []);
    await context.close();
    console.log(`PASS ${width}px off-field create/edit/archive/schedule/completion/delete/cancel/group and arbitrary field cards`);
    }
  } finally { await browser.close(); }
})().catch(error => { console.error(error); process.exitCode=1; });
