"use strict";
const { chromium } = require("C:/Users/Keisuke/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright");
const assert = require("node:assert/strict");
const path = require("node:path");
const os = require("node:os");
(async () => {
  const browser = await chromium.launch({ headless: true, executablePath: "C:/Program Files/Google/Chrome/Application/chrome.exe" });
  try {
    for (const width of [360, 390]) {
      const context = await browser.newContext({ viewport: { width, height: 844 }, isMobile: true, hasTouch: true });
      const page = await context.newPage();
      const errors = [];
      page.on("pageerror", (error) => errors.push(error.message));
      await page.route("https://**/*", (route) => route.abort());
      await page.goto("http://127.0.0.1:4182/index.html", { waitUntil: "networkidle" });
      const fixture = await page.evaluate(() => {
        const R = window.RiceOS;
        const date = R.utils.today();
        const fieldId = R.state.addField("QA completion field");
        const titles = ["幼穂確認", "出穂確認", "草刈り", "深水開始", "中干し開始", "中干し終了", "中干し確認"];
        titles.forEach((title, index) => R.state.saveSchedule({ scheduleId: `qa-completion-${index}`, date, fieldIds: [fieldId], title,
          ...(index === 3 ? { recordKind: "water", waterKind: "deep", waterPhase: "start" } : {}) }));
        return { date, fieldId };
      });
      const stored = () => page.evaluate(() => JSON.parse(localStorage.getItem("rice_os_v8_stable")));
      const schedule = async (index) => (await stored()).schedules.find((row) => row.scheduleId === `qa-completion-${index}`);
      const complete = (index) => page.locator(`[data-calendar-action="complete"][data-id="qa-completion-${index}"]`).click();
      await page.locator('.nav-item[data-screen="calendar"]:visible').click();
      await page.locator("#calendarTargetFilter").selectOption(`field:${fixture.fieldId}`);
      const before = await stored();
      await complete(0);
      assert.equal(await page.locator("#screen-growth.active").count(), 1);
      await page.locator("#appBackButton").click();
      assert.deepEqual(await stored(), before, "Cancelling completion must not complete or save a record");
      await complete(0);
      await page.locator("#gPanicleLengthMm").fill("1.5");
      await page.locator('#growthForm button[type="submit"]').click();
      let done = await schedule(0);
      assert.ok(done.completedAt, "A measured panicle record must complete the exact source schedule");
      assert.equal(done.completionLink.kind, "growth");
      let log = (await stored()).growthLogs.find((row) => row.logId === done.completionLink.recordId);
      assert.equal(log.fieldId, fixture.fieldId);
      assert.equal(Number(log.panicleLengthMm), 1.5);
      assert.ok(!(await schedule(1)).completedAt);
      await page.locator("#appBackButton").click();
      assert.equal(await page.locator('#selectedDateEntries [data-id="qa-completion-0"][data-calendar-action="complete"]').count(), 0);
      await page.locator("#calendarDisplayMode").selectOption("all");
      assert.ok((await page.locator("#selectedDateEntries").innerText()).includes("幼穂確認"));
      await page.screenshot({ path: path.join(os.tmpdir(), `calendar-completion-${width}.png`) });
      assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
      await page.reload({ waitUntil: "networkidle" });
      assert.equal((await schedule(0)).completionLink.recordId, log.logId, "Completion link must survive reload");
      await page.locator('.nav-item[data-screen="calendar"]:visible').click();
      await page.locator("#calendarTargetFilter").selectOption(`field:${fixture.fieldId}`);
      await complete(1);
      await page.locator("#gObservedStage").selectOption("heading");
      await page.locator('#growthForm button[type="submit"]').click();
      assert.ok(!(await schedule(1)).completedAt, "Choosing a stage is not a heading observation");
      await page.locator("#appBackButton").click();
      await complete(1);
      await page.locator("#gHeadingObserved").check();
      await page.locator('#growthForm button[type="submit"]').click();
      await page.locator('[data-heading-confirm="approve"]').click();
      done = await schedule(1);
      assert.ok(done.completedAt);
      log = (await stored()).growthLogs.find((row) => row.logId === done.completionLink.recordId);
      assert.equal(log.headingObserved, true);
      await page.locator("#appBackButton").click();
      await complete(2);
      await page.locator('#fieldWorkForm button[type="submit"]').click();
      assert.ok((await schedule(2)).completedByWorkId);
      await page.locator("#appBackButton").click();
      await complete(3);
      assert.equal(await page.locator("#screen-irrigation.active").count(), 1);
      const beforeWater = await stored();
      await page.locator("#appBackButton").click();
      assert.deepEqual(await stored(), beforeWater, "Cancelling water completion must not write data");
      assert.ok(!(await schedule(3)).completedAt);
      await complete(4);
      page.once("dialog", (dialog) => dialog.dismiss());
      await page.locator('[data-water-action="dry-start"]').click();
      assert.deepEqual(await stored(), beforeWater, "Cancelled water start must not write data");
      page.once("dialog", (dialog) => dialog.accept());
      await page.locator('[data-water-action="dry-start"]').click();
      const dryDone = await schedule(4);
      assert.ok(dryDone.completedByWaterPeriodId, "A title-based water schedule must link its actual start");
      assert.ok(!(await schedule(5)).completedAt);
      await page.locator("#appBackButton").click();
      await complete(5);
      page.once("dialog", (dialog) => dialog.accept());
      await page.locator('[data-water-action="dry-end"]').click();
      assert.equal((await schedule(5)).completedByWaterPeriodId, dryDone.completedByWaterPeriodId);
      assert.equal((await schedule(5)).completionLink.event, "end");
      assert.ok((await schedule(4)).completedAt, "Ending water must not reopen its start schedule");
      await page.locator("#appBackButton").click();
      await page.locator("#calendarDisplayMode").selectOption("all");
      await page.screenshot({ path: path.join(os.tmpdir(), `calendar-water-completion-${width}.png`) });
      assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
      const panicleLogId = (await schedule(0)).completionLink.recordId;
      const growthCard = page.locator('#selectedDateEntries .mini-card').filter({ has: page.locator(`[data-calendar-action="delete"][data-kind="growth"][data-id="${panicleLogId}"]`) });
      await growthCard.locator('summary').click();
      const beforeDelete = await stored();
      page.once("dialog", (dialog) => dialog.dismiss());
      await page.locator(`[data-calendar-action="delete"][data-kind="growth"][data-id="${panicleLogId}"]`).click();
      assert.deepEqual(await stored(), beforeDelete, "Cancelling deletion must retain evidence and completion");
      await growthCard.locator('summary').click();
      page.once("dialog", (dialog) => dialog.accept());
      await page.locator(`[data-calendar-action="delete"][data-kind="growth"][data-id="${panicleLogId}"]`).click();
      assert.ok(!(await schedule(0)).completedAt, "Deleting evidence must reopen only its source schedule");
      assert.ok((await schedule(1)).completedAt);
      assert.ok((await schedule(4)).completedAt);
      assert.ok((await schedule(5)).completedAt);
      const beforeCheck = await stored();
      page.once("dialog", (dialog) => dialog.dismiss());
      await page.locator('[data-calendar-action="confirm"][data-id="qa-completion-6"]').click();
      assert.deepEqual(await stored(), beforeCheck, "Cancelling a confirmation must not write data");
      page.once("dialog", (dialog) => dialog.accept());
      await page.locator('[data-calendar-action="confirm"][data-id="qa-completion-6"]').click();
      assert.equal((await schedule(6)).status, "手動完了");
      assert.deepEqual((await stored()).dryPeriods, beforeCheck.dryPeriods);
      assert.deepEqual((await stored()).irrigations, beforeCheck.irrigations);
      assert.deepEqual(errors, []);
      console.log(`PASS calendar completion ${width}px panicle/heading/work/water start-end/save/reload/cancellation/manual-stage distinction`);
      await context.close();
    }
  } finally { await browser.close(); }
})().catch((error) => { console.error(error); process.exitCode = 1; });
