"use strict";
const { chromium } = require("C:/Users/Keisuke/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright");
const assert = require("node:assert/strict");
const path = require("node:path");
const os = require("node:os");
(async () => {
  const browser = await chromium.launch({ headless: true, executablePath: "C:/Program Files/Google/Chrome/Application/chrome.exe" });
  try {
    for (const width of [360, 390]) {
      const context = await browser.newContext({ viewport: { width, height: 844 }, isMobile: true, hasTouch: true });
      const page = await context.newPage();
      const errors = [];
      page.on("pageerror", (error) => errors.push(error.message));
      await page.route("https://**/*", (route) => route.abort());
      await page.goto("http://127.0.0.1:4182/index.html", { waitUntil: "networkidle" });
      const fixture = await page.evaluate(() => {
        const R = window.RiceOS;
        const date = R.utils.today();
        const groupId = R.state.addFieldGroup("QA calendar group");
        const fieldIds = [R.state.addField("QA calendar A"), R.state.addField("QA calendar B")];
        fieldIds.forEach((id) => R.state.updateField(id, { fieldGroupId: groupId }));
        const shipment = R.state.saveShipment({ date, season: Number(date.slice(0, 4)) - 1, recipient: "QA calendar recipient", kind: "gift", riceType: "brown", packages: [{ kg: 30, bags: 2 }] });
        return { date, groupId, fieldIds, shipmentId: shipment.shipmentId };
      });
      const stored = () => page.evaluate(() => JSON.parse(localStorage.getItem("rice_os_v8_stable")));
      const baseline = await stored();
      const close = () => page.locator("button[data-sheet-close]").click();
      await page.locator('.nav-item[data-screen="calendar"]:visible').click();
      await page.locator("#calendarTargetFilter").selectOption(`field:${fixture.fieldIds[0]}`);
      await page.locator("[data-calendar-add-plan]").click();
      assert.deepEqual(await page.locator('#sheetScheduleFields [aria-pressed="true"]').evaluateAll((nodes) => nodes.map((node) => node.dataset.sheetField)), [fixture.fieldIds[0]]);
      await close();
      assert.deepEqual(await stored(), baseline, "Closing an unsaved plan must not write data");
      await page.locator("#calendarTargetFilter").selectOption(`group:${fixture.groupId}`);
      await page.locator("[data-calendar-add-plan]").click();
      assert.equal(await page.locator("#sheetScheduleTargetMode").inputValue(), "group");
      assert.equal(await page.locator("#sheetScheduleGroup").inputValue(), fixture.groupId);
      await page.locator("#sheetScheduleTitle").fill("QA group mowing");
      await page.screenshot({ path: path.join(os.tmpdir(), `calendar-group-input-${width}.png`) });
      assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
      await page.locator('#sheetScheduleForm button[type="submit"]').click();
      let data = await stored();
      const plans = data.schedules.filter((row) => row.title === "QA group mowing");
      assert.equal(plans.length, 2);
      assert.deepEqual(plans.flatMap((row) => row.fieldIds).sort(), fixture.fieldIds.slice().sort());
      assert.ok(plans.every((row) => row.date === fixture.date));
      assert.deepEqual(data.fieldWorks, baseline.fieldWorks);
      assert.deepEqual(data.irrigations, baseline.irrigations);
      await close();
      assert.equal(await page.locator('#selectedDateEntries [data-calendar-action="complete"]').count(), 2);
      await page.locator("#calendarTargetFilter").selectOption(`field:${fixture.fieldIds[1]}`);
      const expectedPlan = plans.find((row) => row.fieldIds.includes(fixture.fieldIds[1]));
      assert.equal(await page.locator('#selectedDateEntries [data-calendar-action="complete"]').count(), 1);
      assert.equal(await page.locator('#selectedDateEntries [data-calendar-action="complete"]').getAttribute("data-id"), expectedPlan.scheduleId, "A field filter must never expose another field's batch sibling for mutation");
      await page.locator("#calendarTargetFilter").selectOption(`group:${fixture.groupId}`);
      await page.locator("[data-calendar-add-record]").click();
      await page.locator('[data-sheet-add="work"]').click();
      assert.equal(await page.locator("#sheetTargetMode").inputValue(), "group");
      assert.equal(await page.locator("#sheetGroup").inputValue(), fixture.groupId);
      await page.locator("#sheetOpenRecord").click();
      assert.equal(await page.locator("#screen-field-work.active").count(), 1);
      assert.equal(await page.locator("#fwDate").inputValue(), fixture.date);
      await page.locator("#appBackButton").click();
      assert.equal(await page.locator("#screen-calendar.active").count(), 1);
      assert.equal(await page.locator("#calendarTargetFilter").inputValue(), `group:${fixture.groupId}`);
      assert.deepEqual(await stored(), data, "Cancelled work input must not write data");
      await page.locator('#selectedDateEntries .calendar-entry-menu summary').first().click();
      let editDialogCount = 0;
      const editDialog = async (dialog) => {
        editDialogCount++;
        await dialog.accept(editDialogCount === 1 ? "QA group edited" : "QA edit memo");
      };
      page.on("dialog", editDialog);
      await page.locator('#selectedDateEntries [data-calendar-action="edit"]').first().click();
      page.off("dialog", editDialog);
      assert.equal(editDialogCount, 2);
      data = await stored();
      const edited = data.schedules.find((row) => row.title === "QA group edited");
      assert.ok(plans.some((row) => row.scheduleId === edited.scheduleId));
      await page.locator('#selectedDateEntries .calendar-entry-menu summary').first().click();
      page.once("dialog", (dialog) => dialog.dismiss());
      await page.locator(`#selectedDateEntries [data-calendar-action="delete"][data-id="${edited.scheduleId}"]`).click();
      assert.deepEqual(await stored(), data, "Cancelled delete must not write data");
      await page.locator('#selectedDateEntries .calendar-entry-menu summary').first().click();
      page.once("dialog", (dialog) => dialog.accept());
      await page.locator(`#selectedDateEntries [data-calendar-action="delete"][data-id="${edited.scheduleId}"]`).click();
      assert.ok(!(await stored()).schedules.some((row) => row.scheduleId === edited.scheduleId));
      await page.locator("#calendarTargetFilter").selectOption("offField");
      await page.locator("[data-calendar-add-plan]").click();
      assert.equal(await page.locator("#sheetScheduleTargetMode").inputValue(), "offField");
      await close();
      await page.locator("[data-calendar-add-record]").click();
      await page.locator('[data-sheet-add="work"]').click();
      assert.equal(await page.locator("#sheetTargetMode").inputValue(), "offField");
      await page.locator("#sheetOpenRecord").click();
      assert.equal(await page.locator("#fwTargetScope").inputValue(), "offField");
      await page.locator("#appBackButton").click();
      await page.locator("#calendarDisplayMode").selectOption("all");
      await page.locator(`[data-calendar-open-shipment="${fixture.shipmentId}"]`).click();
      assert.equal(await page.locator("#screen-shipments.active").count(), 1);
      assert.ok((await page.locator(".shipment-detail-head").innerText()).includes("QA calendar recipient"));
      await page.locator("#appBackButton").click();
      await page.locator("#appBackButton").click();
      assert.equal(await page.locator("#screen-calendar.active").count(), 1);
      await page.locator("#calendarTargetFilter").selectOption("all");
      const beforeShipmentView = await stored();
      await page.locator("[data-calendar-add-record]").click();
      await page.locator(`[data-sheet-open-shipment="${fixture.shipmentId}"]`).click();
      assert.ok((await page.locator(".shipment-detail-head").innerText()).includes("QA calendar recipient"));
      await page.locator("#appBackButton").click();
      await page.locator("#appBackButton").click();
      assert.equal(await page.locator("#screen-calendar.active").count(), 1);
      assert.deepEqual(await stored(), beforeShipmentView, "Viewing a shipment through the date sheet must not write data");
      await page.locator("[data-calendar-add-plan]").click();
      assert.equal(await page.locator('#sheetScheduleFields [aria-pressed="true"]').count(), 0, "All-display filter must not select all fields for input");
      await close();
      assert.deepEqual(errors, []);
      console.log(`PASS calendar ${width}px target prefill/group save/edit/delete/cancellation/shipment/back`);
      await context.close();
    }
  } finally { await browser.close(); }
})().catch((error) => { console.error(error); process.exitCode = 1; });
