"use strict";
const { chromium } = require("C:/Users/Keisuke/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright");
const assert = require("node:assert/strict");
const path = require("node:path");
const os = require("node:os");

(async () => {
  const browser = await chromium.launch({ headless: true, executablePath: "C:/Program Files/Google/Chrome/Application/chrome.exe" });
  try {
    for (const width of [360, 390]) {
      const context = await browser.newContext({ viewport: { width, height: 844 }, isMobile: true, hasTouch: true });
      const page = await context.newPage();
      const errors = [];
      page.on("pageerror", error => errors.push(error.message));
      await page.route("https://**/*", route => route.abort());
      await page.goto("http://127.0.0.1:4182/index.html", { waitUntil: "networkidle" });
      const f = await page.evaluate(() => {
        const R = window.RiceOS, date = R.utils.today();
        const a = R.state.addField("QA completed"), b = R.state.addField("QA partial"), c = R.state.addField("QA legacy");
        const group = R.state.addFieldGroup("QA grouping");
        [a,b,c].forEach(id => R.state.updateField(id, { fieldGroupId: group }));
        R.state.updateField(a, { nextSeasonMemo: "Legacy unchanged" });
        R.state.saveFieldWork({ workId: "qa-complete", date, workName: "稲刈り", fieldIds: [a], harvestStatusByField: { [a]: "complete" } });
        R.state.saveFieldWork({ workId: "qa-partial", date, workName: "稲刈り", fieldIds: [b], harvestStatusByField: { [b]: "partial" } });
        R.state.saveFieldWork({ workId: "qa-legacy", date, workName: "稲刈り", fieldIds: [c] });
        R.app.show("home");
        return { a,b,c,group,date,year:date.slice(0,4) };
      });
      const stored = () => page.evaluate(() => localStorage.getItem("rice_os_v8_stable"));
      const before = await stored();
      await page.locator("[data-home-group-filter]").selectOption(f.group);
      assert.match(await page.locator(".home-harvest-count").innerText(), /1\/3/);
      assert.equal(await page.locator("[data-home-harvest-completed]").evaluate(el => el.open), false);
      assert.equal(await page.locator(`[data-home-unharvested-fields] [data-home-stage-card="${f.a}"]`).count(), 0);
      for (const id of [f.b,f.c]) assert.equal(await page.locator(`[data-home-unharvested-fields] [data-home-stage-card="${id}"]`).count(), 1);
      await page.locator("[data-home-harvest-completed] > summary").click();
      await page.locator(`[data-home-harvest-completed] [data-home-toggle-field="${f.a}"]`).click();
      assert.equal(await page.locator("[data-home-harvest-completed]").evaluate(el => el.open), true);
      assert.equal(await stored(), before, "Viewing/filtering must not mutate data");
      await page.screenshot({ path: path.join(os.tmpdir(), `harvest-home-${width}.png`), fullPage: true });
      await page.evaluate(({date,b}) => { const R=window.RiceOS; R.app.openInput("field-work","home"); R.screens.fieldWork.prefillDate(date,b); }, f);
      await page.locator("#fwName").selectOption("稲刈り");
      assert.equal(await page.locator("#fwHarvestQuickReview #fwHarvestSurface").count(), 1);
      assert.equal(await page.locator("#fwHarvestQuickReview #fwHarvestWeeds").count(), 1);
      assert.equal(await page.locator("#fwHarvestQuickReview #fwMemo").count(), 1);
      await page.locator("#fwHarvestSurface").selectOption({ label: "適度" });
      await page.locator("#fwHarvestWeeds").selectOption({ label: "少し" });
      await page.locator("#fwMemo").fill("Quick optional reflection");
      await page.screenshot({ path: path.join(os.tmpdir(), `harvest-quick-${width}.png`), fullPage: true });
      await page.locator("#appBackButton").click();
      assert.equal(await stored(), before, "Cancelling optional input must not write data");
      await page.evaluate(({date,b})=>{const R=window.RiceOS; R.app.openInput("field-work","home"); R.screens.fieldWork.prefillDate(date,b);},f);
      await page.locator("#fwName").selectOption("稲刈り");
      await page.locator(`[data-harvest-field="${f.b}"][value="partial"]`).check();
      await page.locator("#fwHarvestSurface").selectOption({label:"適度"});
      await page.locator("#fwHarvestWeeds").selectOption({label:"少し"});
      await page.locator("#fwMemo").fill("Quick saved reflection");
      await page.locator('#fieldWorkForm button[type="submit"]').click();
      await page.waitForFunction(()=>window.RiceOS.state.data().fieldWorks.some(w=>w.memo==="Quick saved reflection"));
      const quick=await page.evaluate(()=>window.RiceOS.state.data().fieldWorks.find(w=>w.memo==="Quick saved reflection"));
      assert.equal(quick.harvestReview.surface,"適度");
      assert.equal(quick.harvestReview.weeds,"少し");
      const beforeCarryover=await stored();
      await page.locator('.nav-item[data-screen="annual"]:visible').click();
      await page.locator("#annualYear").selectOption(f.year);
      await page.evaluate(id => window.RiceOS.screens.annual.openField(id,"work"), f.a);
      await page.locator(".annual-legacy-carryover > summary").first().click();
      await page.locator("[data-carryover-copy]").first().click();
      assert.equal(await page.locator("[data-carryover-text]").inputValue(), "Legacy unchanged");
      await page.locator("[data-carryover-cancel]").click();
      assert.equal(await stored(), beforeCarryover, "Copy preview/cancel must preserve the old record");
      await page.locator("[data-carryover-add]").first().click();
      await page.locator("[data-carryover-text]").fill("Current year handover");
      await page.locator("[data-carryover-save]").click();
      assert.equal(await page.evaluate(({a,year}) => window.RiceOS.state.carryoverNoteForField(a,year).text, f), "Current year handover");
      assert.equal(await page.evaluate(a => window.RiceOS.state.field(a).nextSeasonMemo,f.a), "Legacy unchanged");
      await page.locator("[data-carryover-edit]").first().click();
      await page.locator("[data-carryover-text]").fill("Current year handover revised");
      await page.locator("[data-carryover-save]").click();
      await page.evaluate(({a,year})=>{const R=window.RiceOS; R.state.saveCarryoverNote({fieldId:a,season:String(Number(year)-1),text:"Previous year untouched"});},f);
      assert.equal(await page.evaluate(({a,year})=>window.RiceOS.state.carryoverNoteForField(a,String(Number(year)-1))?.text,f),"Previous year untouched");
      const yieldBefore=await stored();
      await page.locator("[data-annual-harvest-edit]").first().click();
      assert.equal(await page.locator("#screen-field-work.active").count(),1);
      assert.equal(await page.locator("#editFieldWorkId").inputValue(),"qa-complete");
      await page.locator("#fwHarvestYieldKg").fill("123");
      await page.locator("#appBackButton").click();
      assert.match(await page.locator(".annual-detail-head").innerText(),/QA completed/);
      assert.equal(await stored(),yieldBefore,"Cancelling yield edit must not write records");
      const thermal = await page.evaluate(() => {
        const R=window.RiceOS, date=R.utils.dateAddDays(R.utils.today(),-1);
        const d=R.state.addField("QA thermal");
        R.state.saveGrowthLog({ fieldId:d,date:R.utils.dateAddDays(date,-3),headingObserved:true });
        R.state.updateWeatherLocation({latitude:37.7,longitude:140.4,label:"QA"});
        R.state.saveFieldWork({workId:"qa-thermal",date,workName:"稲刈り",fieldIds:[d],harvestStatusByField:{[d]:"complete"}});
        R.weather.fetchDailyRange=()=>new Promise(resolve=>{ window.qaResolve=resolve; });
        R.screens.annual.openField(d,"work");
        return {d,date};
      });
      const retryBefore=await stored();
      await page.locator('[data-harvest-thermal-retry="qa-thermal"]').click();
      assert.equal(await page.locator('[data-harvest-thermal-retry="qa-thermal"]').isDisabled(),true);
      await page.locator('[data-harvest-thermal-cancel="qa-thermal"]').click();
      await page.evaluate(()=>window.qaResolve({count:3,total:72,rows:[],retrievedAt:"QA"}));
      await page.waitForFunction(()=>!document.querySelector('[data-harvest-thermal-cancel="qa-thermal"]'));
      assert.equal(await stored(),retryBefore,"Cancelled fetch must not change saved snapshots");
      await page.evaluate(()=>{ window.RiceOS.weather.fetchDailyRange=async()=>{throw new Error("QA failure");}; });
      await page.locator('[data-harvest-thermal-retry="qa-thermal"]').click();
      await page.waitForFunction(()=>!document.querySelector('[data-harvest-thermal-cancel="qa-thermal"]'));
      assert.equal(await stored(),retryBefore,"Failed fetch must preserve saved data");
      await page.evaluate(()=>{ window.RiceOS.weather.fetchDailyRange=async()=>({count:3,total:72,rows:[{dataset:"QA deterministic"}],retrievedAt:"QA"}); });
      await page.locator('[data-harvest-thermal-retry="qa-thermal"]').click();
      await page.waitForFunction(({d})=>window.RiceOS.state.data().fieldWorks.find(w=>w.workId==="qa-thermal").harvestSnapshots.find(s=>s.fieldId===d).thermal?.total===72,thermal);
      assert.equal(await page.locator('[data-harvest-thermal-retry="qa-thermal"]').count(),0,"Complete historical snapshot must not be overwritten");
      await page.screenshot({path:path.join(os.tmpdir(),`harvest-followup-${width}.png`),fullPage:true});
      await page.reload({ waitUntil:"networkidle" });
      assert.equal(await page.evaluate(({a,year}) => window.RiceOS.state.carryoverNoteForField(a,year).text, f), "Current year handover revised");
      await page.locator('.nav-item[data-screen="annual"]:visible').click();
      await page.locator("#annualYear").selectOption(f.year);
      await page.evaluate(id=>window.RiceOS.screens.annual.openField(id,"work"),f.a);
      const deleteBefore=await stored();
      page.once("dialog",dialog=>dialog.dismiss());
      await page.locator("[data-carryover-delete]").first().click();
      assert.equal(await stored(),deleteBefore);
      page.once("dialog",dialog=>dialog.accept());
      await page.locator("[data-carryover-delete]").first().click();
      assert.equal(await page.evaluate(({a,year})=>window.RiceOS.state.carryoverNoteForField(a,year),f),null);
      assert.equal(await page.evaluate(({a,year})=>window.RiceOS.state.carryoverNoteForField(a,String(Number(year)-1)).text,f),"Previous year untouched");
      assert.equal(await page.evaluate(a=>window.RiceOS.state.field(a).nextSeasonMemo,f.a),"Legacy unchanged");
      assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > document.documentElement.clientWidth), false);
      assert.deepEqual(errors, []);
      console.log(`PASS followup ${width}px home folding/counts/view-only, quick fields/cancel, yearly memo/copy/reload, yield edit/back/cancel, thermal cancel/failure/success`);
      await context.close();
    }
  } finally { await browser.close(); }
})().catch(error => { console.error(error); process.exitCode=1; });
